const actionTypes = {
  INIT_START: 'INIT_START',
  SUCCESS_INIT: 'SUCCESS_INIT',
  FAILED_INIT: 'FAILED_INIT',
  INFO_SUCCESS: 'INFO_SUCCESS',
  INFO_FAILED: 'INFO_FAILED',
  FRIENDS_INFO_SUCCESS: 'FRIENDS_INFO_SUCCESS',
  FRIENDS_INFO_FAILED: 'FRIENDS_INFO_FAILED',
  SEARCH_SET_QUERY: 'SEARCH_SET_QUERY',
  FAILED_SEARCH: 'FAILED_SEARCH',
  FRIENDS_REQUEST: 'FRIENDS_REQUEST',
  FRIENDS_SUCCESS: 'FRIENDS_SUCCESS',
  FRIENDS_FAILED: 'FRIENDS_FAILED',
  FRIENDS_SET_QUERY: 'FRIENDS_SET_QUERY',
  FRIENDS_SUCCESS_SEARCH: 'FRIENDS_SUCCESS_SEARCH',
  FRIENDS_FAILED_SEARCH: 'FRIENDS_FAILED_SEARCH',
  ADD_TO_WISH_LIST: 'ADD_TO_WISH_LIST',
  DELETE_FROM_WISH: 'DELETE_FROM_WISH',
  BOOKS_REQUEST: 'BOOKS_REQUEST',
  BOOKS_SUCCESS: 'BOOKS_SUCCESS',
  BOOKS_ERROR: 'BOOKS_ERROR',
};

export default actionTypes;
